apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: coyz83dxz-python
  janus-idp.io/tekton: coyz83dxz-python
  backstage.io/kubernetes-id: coyz83dxz-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: coyz83dxz-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
