apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: coyz83dxz-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: coyz83dxz-python 
  name: coyz83dxz-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: coyz83dxz-python 
