apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: coyz83dxz-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:92b94f2d926e8e4e8ba0bd606e58683b48f9c4a1@sha256:89dcc46828b87be852cbdbd73e100e0cf0542d3cb34f118cb6e1ba195f40581a
          name: container-image
